const selectOptions = {
  gender: [
    { value: "", label: "Select value" },
    { value: "male", label: "Male" },
    { value: "female", label: "Female" },
  ],
  religion: [
    { value: "", label: "Select value" },
    { value: "hindu", label: "Hindu" },
    { value: "sikh", label: "Sikh" },
    { value: "jain", label: "Jain" },
    { value: "buddhist", label: "Buddhist" },
  ],
  marital_status: [
    { value: "", label: "Select value" },
    { value: "never_married", label: "Never Married" },
    { value: "divorced", label: "Divorced" },
    { value: "widow_widower", label: "Widow/Widower" },
    { value: "awaiting_divorce", label: "Awaiting Divorce" },
  ],
  caste: [
    { value: "", label: "Select value" },
    { value: "khatri", label: "Khatri" },
    { value: "arora", label: "Arora" },
    { value: "brahmin", label: "Brahmin" },
    { value: "other", label: "Other" },
  ],
  mangalik: [
    { value: "", label: "Select value" },
    { value: "non_manglik", label: "Non Manglik" },
    { value: "manglik", label: "Manglik" },
    { value: "partial_manglik", label: "Partial Manglik" },
  ],
  family_value: [
    { value: "", label: "Select value" },
    { value: "orthodox", label: "Orthodox" },
    { value: "traditional", label: "Traditional" },
    { value: "liberal", label: "Liberal" },
    { value: "modern", label: "Modern" },
  ],
  family_type: [
    { value: "", label: "Select value" },
    { value: "nuclear", label: "Nuclear Family" },
    { value: "joint", label: "Joint Family" },
    { value: "extended", label: "Extended Family" },
    { value: "living_alone", label: "Living Alone" },
  ],
  education_level: [
    { value: "", label: "Select value" },
    { value: "high_school", label: "High School" },
    { value: "undergraduate", label: "Undergraduate" },
    { value: "graduate", label: "Graduate" },
    { value: "post_graduate", label: "Post Graduate" },
    { value: "doctorate", label: "Doctorate" },
  ],
  education_field: [
    { value: "", label: "Select value" },
    { value: "engineering", label: "Engineering" },
    { value: "medical", label: "Medical" },
    { value: "commerce", label: "Commerce" },
    { value: "arts", label: "Arts" },
    { value: "science", label: "Science" },
    { value: "other", label: "Other" },
  ],
  skin_tone: [
    { value: "", label: "Select value" },
    { value: "very_fair", label: "Very Fair" },
    { value: "fair", label: "Fair" },
    { value: "wheatish", label: "Wheatish" },
    { value: "dark", label: "Dark" },
  ],
  body_type: [
    { value: "", label: "Select value" },
    { value: "slim", label: "Slim" },
    { value: "athletic", label: "Athletic" },
    { value: "average", label: "Average" },
    { value: "heavy", label: "Heavy" },
  ],
  physical_disability: [
    { value: "", label: "Select value" },
    { value: "false", label: "No" },
    { value: "true", label: "Yes" },
  ],
  smoke: [
    { value: "", label: "Select value" },
    { value: "no", label: "No" },
    { value: "yes", label: "Yes" },
    { value: "occasionally", label: "Occasionally" },
  ],
  drink: [
    { value: "", label: "Select value" },
    { value: "no", label: "No" },
    { value: "yes", label: "Yes" },
    { value: "occasionally", label: "Occasionally" },
  ],
  veg_nonveg: [
    { value: "", label: "Select value" },
    { value: "veg", label: "Vegetarian" },
    { value: "nonveg", label: "Non-Vegetarian" },
    { value: "occasionally_nonveg", label: "Occasionally Non-Vegetarian" },
  ],
  nri_status: [
    { value: "", label: "Select value" },
    { value: "false", label: "No" },
    { value: "true", label: "Yes" },
  ],
};

export default selectOptions;
